image: node:latest
stages:
  - install
  - start
  - cleanup

compile:
  stage: install
  script:
    - npm install && npm -G install ts-node typescript
  cache:
   paths:
     - node_modules/
    
 
release-image:
  stage: start
  script:
    - npm start
  only:
    - master
    - release
 
cleanup:
  stage: cleanup
  when: always
  script:
    - echo "Stop & remove containers"
