image: node:latest
stages:
  - install
  - start
  
compile:
  stage: install
  script:
    - npm install && npm -G install ts-node typescript
   
release-image:
  stage: start
  script:
    - npm install && npm install ts-node typescript && npm start stop
  only:
    - master
    - release
 
